on:
  workflow_dispatch:

  push:
    branches:
      - "main"
      - "initial"

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - run: |
          pip install s3cmd
          s3cmd --help
