on:
  workflow_dispatch:

  push:
    branches:
      - "main"
      - "initial"

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.U316870_STORAGE_BOX_SSH_PRIVATE_KEY }}
          known_hosts: "just-a-placeholder-so-we-dont-get-errors"
      - uses: actions/checkout@v2
      - run: |
          ls -lR
          pip install s3cmd

          ### GENERATE S3CFG
          cat << EOF > ~/.s3cfg
          host_base = $S3HOST
          host_bucket = $S3HOST
          bucket_location = eu-central-1
          use_https = True
          access_key = ${S3ACCESS}
          secret_key = ${S3SECRET}
          signature_v2 = False
          EOF

          s3cmd ls

          ssh -o StrictHostKeyChecking=no -p 23 ${STORAGEBOX_SSH_ADDRESS} ls

        env:
          S3HOST: "minio.ci4rail.com"
          S3ACCESS: ${{ secrets.MINIO_ACCESS_KEY }}
          S3SECRET: ${{ secrets.MINIO_SECRET_KEY }}
          STORAGEBOX_SSH_ADDRESS: "u316870@u316870.your-storagebox.de"
