on:
  workflow_dispatch:

  push:
    branches:
      - "main"
      - "initial"

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - run: |
          pip install s3cmd

          cat << EOF > ~/.s3cfg
          host_base = $S3HOST
          host_bucket = $S3HOST
          bucket_location = eu-central-1
          use_https = True

          access_key = ${S3ACCESS}
          secret_key = ${S3SECRET}

          signature_v2 = False
          EOF

          cat ~/.s3cfg
          s3cmd ls

          mkdir -p ~/.ssh
          echo ${STORAGEBOX_SSH_PRIVATE_KEY} >~/.ssh/id.rsa
          cat ~/.ssh/id.rsa
          ssh -o StrictHostKeyChecking=no -p 23 ${STORAGEBOX_SSH_ADDRESS} ls

        env:
          S3HOST: "minio.ci4rail.com"
          S3ACCESS: ${{ secrets.MINIO_ACCESS_KEY }}
          S3SECRET: ${{ secrets.MINIO_SECRET_KEY }}
          STORAGEBOX_SSH_PRIVATE_KEY: ${{ secrets.U316870_STORAGE_BOX_SSH_PRIVATE_KEY }}
          STORAGEBOX_SSH_ADDRESS: "u316870@u316870.your-storagebox.de"
