on:
  workflow_dispatch:

  push:
    branches:
      - "main"
      - "initial"

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - run: |
          pip install s3cmd

          cat << EOF
          host_base = $S3HOST
          EOF > ~/.s3cfg
          cat ~/.s3cfg

        env:
          S3HOST: "minio.ci4rail.com"
